"use client";
import { RotateCcw, SlidersHorizontal } from "lucide-react";
import { propertyTypes } from "@/lib/properties";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
export type Filters = { zone: string; operation: string; type: string; price: string; bedrooms: string; minLand: string };
export function FilterBar({ filters, onChange, onReset, count }: { filters: Filters; onChange: (next: Filters) => void; onReset: () => void; count: number }) {
  const set = (key: keyof Filters, value: string) => onChange({ ...filters, [key]: value });
  return <aside className="filter-panel"><div className="filter-title"><SlidersHorizontal size={20} /><strong>Filtrar catálogo</strong><span>{count} resultados</span></div><label>Zona<input value={filters.zone} onChange={(e) => set("zone", e.target.value)} placeholder="Ej. Ánimas o Coatepec" /></label><label>Operación<Select value={filters.operation} onValueChange={(v) => set("operation", v)}><SelectTrigger className="filter-select"><SelectValue /></SelectTrigger><SelectContent>{["Todos","Venta","Renta","Inversión"].map(v => <SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></label><label>Tipo de inmueble<Select value={filters.type} onValueChange={(v) => set("type", v)}><SelectTrigger className="filter-select"><SelectValue /></SelectTrigger><SelectContent>{propertyTypes.map(v => <SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></label><label>Precio máximo<Select value={filters.price} onValueChange={(v) => set("price", v)}><SelectTrigger className="filter-select"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="Todos">Sin límite</SelectItem><SelectItem value="2000000">$2,000,000</SelectItem><SelectItem value="4000000">$4,000,000</SelectItem><SelectItem value="7000000">$7,000,000</SelectItem></SelectContent></Select></label><label>Recámaras<Select value={filters.bedrooms} onValueChange={(v) => set("bedrooms", v)}><SelectTrigger className="filter-select"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="Todos">Cualquiera</SelectItem><SelectItem value="2">2+</SelectItem><SelectItem value="3">3+</SelectItem><SelectItem value="4">4+</SelectItem></SelectContent></Select></label><label>Terreno mínimo<input type="number" min="0" value={filters.minLand} onChange={(e) => set("minLand", e.target.value)} placeholder="m²" /></label><button className="reset-button" onClick={onReset}><RotateCcw size={17} /> Limpiar filtros</button></aside>;
}
