import Link from "next/link";
import { notFound } from "next/navigation";
import { Bath, BedDouble, CarFront, Check, ChevronLeft, FileCheck2, LandPlot, MapPin, Ruler } from "lucide-react";
import { Header } from "@/components/Header";
import { ContactForm } from "@/components/ContactForm";
import { Footer } from "@/components/Footer";
import { properties } from "@/lib/properties";
export function generateStaticParams() { return properties.map((property) => ({ slug: property.slug })); }
export default async function PropertyDetail({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const property = properties.find((item) => item.slug === slug); if (!property) notFound(); const whatsapp = `https://wa.me/?text=${encodeURIComponent(`Hola Raíz Noble, quiero la ficha completa de ${property.title}.`)}`;
  return <><Header /><main className="detail-page"><div className="container detail-top"><Link href="/propiedades" className="back-link"><ChevronLeft size={18} /> Volver al catálogo</Link><span className="property-tag">{property.operation}</span><h1>{property.title}</h1><p><MapPin size={18} />{property.location}</p></div><div className="container property-gallery"><div className="gallery-main"><img src={property.gallery[0]} alt={property.title} /></div>{property.gallery.slice(1, 3).map((image, index) => <div className="gallery-side" key={image}><img src={image} alt={`Vista ${index + 2} de ${property.title}`} /></div>)}</div><section className="section detail-section"><div className="container detail-layout"><article className="detail-content"><span className="detail-price">{property.priceLabel}</span><h2>Una propiedad para vivir, invertir y construir futuro.</h2><p className="lead">{property.description}</p><div className="detail-stats">{property.land > 0 && <div><LandPlot /><strong>{property.land} m²</strong><span>Terreno</span></div>}{property.construction > 0 && <div><Ruler /><strong>{property.construction} m²</strong><span>Construcción</span></div>}{property.bedrooms > 0 && <div><BedDouble /><strong>{property.bedrooms}</strong><span>Recámaras</span></div>}{property.bathrooms > 0 && <div><Bath /><strong>{property.bathrooms}</strong><span>Baños</span></div>}{property.parking > 0 && <div><CarFront /><strong>{property.parking}</strong><span>Estacionamientos</span></div>}</div><div className="detail-block"><h3>Estado documental</h3><p><FileCheck2 size={22} /> {property.documentStatus}</p></div><div className="detail-block"><h3>Amenidades y características</h3><div className="amenity-grid">{property.amenities.map((item) => <span key={item}><Check size={17} />{item}</span>)}</div></div><div className="location-panel"><MapPin size={30} /><div><h3>Ubicación</h3><p>{property.location}. La ubicación exacta se comparte al confirmar una visita.</p></div></div></article><aside className="detail-sidebar"><div className="visit-card"><span className="eyebrow">Visita privada</span><h2>Agenda tu recorrido</h2><p>Solicita la ficha completa o agenda una visita con acompañamiento profesional.</p><ContactForm propertyTitle={property.title} /><a className="button outline full-width" href={whatsapp} target="_blank" rel="noreferrer">Preguntar por WhatsApp</a></div></aside></div></section></main><Footer /><a className="floating-whatsapp" href={whatsapp} target="_blank" rel="noreferrer" aria-label="Preguntar por esta propiedad en WhatsApp">WA</a></>;
}
